[package]
name = "helios-master-backend"
version = "0.2.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
axum = "0.7.5"
axum-extra = { version = "0.9.3", features = ["typed-header"] }
chrono = { version = "0.4", features = ["serde"] }
deadpool-diesel = { version = "0.4", features = ["postgres"] }
diesel = { version = "2.1.0", features = [
    "postgres",
    "uuid",
    "serde_json",
    "chrono",
] }
dotenvy = "0.15"
jsonwebtoken = "9.3.0"
listenfd = "1.0.1"
log = { version = "0.4", features = ["max_level_debug"] }
once_cell = "1.19.0"
rand_core = { version = "0.6.3", features = ["std"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["macros", "macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
utoipa = { version = "4.2", features = ["axum_extras", "chrono", "uuid"] }
utoipa-swagger-ui = { version = "6", features = ["axum"] }
uuid = { version = "1.4", features = [
    "serde",
    "v4",
    "fast-rng",
    "macro-diagnostics",
] }
validator = { version = "0.18", features = ["derive"] }
