[package]
name = "rust-master-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
diesel = { version = "2.1.0", features = ["postgres", "uuid", "serde_json"] }
deadpool-diesel = { version = "0.4", features = ["postgres"] }
tokio = { version = "1.0", features = ["macros", "macros", "rt-multi-thread"] }
dotenvy = "0.15"
jsonwebtoken = "9.3.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.4", features = [
    "serde",
    "v4",
    "fast-rng",
    "macro-diagnostics",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
validator = { version = "0.18", features = ["derive"] }
log = { version = "0.4", features = ["max_level_debug"] }
listenfd = "1.0.1"
chrono = "0.4.38"
argon2 = "0.5.3"
rand_core = { version = "0.6.3", features = ["std"] }
