global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'helios-monitor'

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: traefik
    metrics_path: /metrics
    static_configs:
      - targets:
        - traefik:8080
  
  - job_name: /loki
    metrics_path: /metrics
    static_configs:
      - targets: 
        - loki:3100
  
  - job_name: /master-backend
    metrics_path: /metrics
    static_configs:
      - targets: 
        - master-backend:${MASTER_METRICS_PORT:-8081}