name: Release

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-hotfix.*"
      - "v*.*.*-nightly"
      - "v*.*.*-alpha"
      - "v*.*.*-beta"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
